# Generated by Django 2.2.12 on 2020-10-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_wedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wedding',
            old_name='alt1',
            new_name='alt',
        ),
    ]
